sudo: required
services:
    - docker

script:
    - docker build -t paultorvik/node .
    - docker images paultorvik/node

before_deploy:
#    - docker login -u  -p 

deploy:
    provider: script
    script: docker push paultorvik/node
    on:
        branch: master
